# This rule is not used by the project cninf itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to cninf.nadavleva.github.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cninf
    app.kubernetes.io/managed-by: kustomize
  name: objstore-viewer-role
rules:
- apiGroups:
  - cninf.nadavleva.github.io
  resources:
  - objstores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cninf.nadavleva.github.io
  resources:
  - objstores/status
  verbs:
  - get
